name: Mock SonarQube

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  mock-sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Pretend to run SonarQube
        run: echo "Mock SonarQube passed"
